### PR TITLE
Fix  ggplot bar stacked dodged

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
Fixed ggplot_bar_stacked_dodged(). 
@giannou Please review and don't merge upstream.

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
@giannou I decided to rework this. 
`add_stacked_dodged_xpos()` and `calc_stacked_dodged_xlabels()` are useable and there is an example for how to make figures.  Still need to wrap it up in a new `ggplot_bar_stacked_dodged()`.

**Comment by giannou** [comment]
can't seem to make it work:
Screenshot 2019-12-17 21 20 46
Here's my data file:
[datai1.rds.gz](https://github.com/giannou/quitte/files/3975297/datai1.rds.gz)

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
I abandoned `ggplot_bar_stacked_dodged()` and will rebuild it with the two new functions.  Use this instead:
```
ggplot() + 
    geom_col(data = add_stacked_dodged_xpos(datai1, c('variable', 'cdrscen')),
             mapping = aes(x = xpos, y = indic, fill = factor)) + 
    scale_x_continuous(
        breaks = calc_stacked_dodged_xlabels(datai1, 
                                             c('variable', 'cdrscen'))) + 
    coord_flip()
```
foo

**Comment by giannou** [comment]
> @giannou I decided to rework this.
> `add_stacked_dodged_xpos()` and `calc_stacked_dodged_xlabels()` are useable and there is an example for how to make figures. Still need to wrap it up in a new `ggplot_bar_stacked_dodged()`.

ah sorry I didn't see that yesterday and kept trying with the `ggplot_bar_stacked_dodged()`. thanks, I'll give it one more try now

**Pull request closed without merging**
